### ISSUE TITLE
promisify("module_name") rewrite module functions

### ISSUE THREAD

**Issue by darrrk** [nodegit/promisify-node#12]
Example:
    
```javascript
var promisify = require("promisify-node"),
  fs = promisify("fs"),
  native_fs = require("fs");

fs.readFile === native_fs.readFile // true
```

This behavior destructive, because promisify no should to rewrite common used modules.

**Comment by maxkorp** [comment]
Yeah, this isn't really meant to be used to use on external modules, it's used to bulk promisify the methods inside of nodegit. Is nodegit causing some other module to be promisified that you load elsewhere?

**Comment by darrrk** [comment]
I use it without nodegit.

**Comment by jon-hall** [comment]
I was also getting this issue and was banging my head against a wall wondering why this (fairly simple) app wasn't working:

```js
const koa = require('koa'),
    server = require('koa-static'),
    co = require('co'),
    promisify = require('promisify-node'),
    fs = promisify('fs');

co(function*() {
    // Do some stuff with the file-system before starting web server
    yield fs.doStuff();

    koa()
        .use(serve('public'))
        .listen(3000, function(){ 
            console.log('Now listening on 3000...'); 
        });
});
```

None of my public content was being served, requests just timed out.  Eventually I put two and two together and figured out `promisify` was mutating `fs` for all consumers, leaving it with an API that `koa-static` couldn't use.

**Comment by tbranyen** [comment]
Looks like we merged your PR. Closing this.
