### ISSUE TITLE
Webpack support

### ISSUE THREAD

**Issue by kmalakoff** [nodegit/promisify-node#16]
It looks like the following lines doing dynamic requires is causing problems for webpack because it cannot be statically analyzed:

```
https://github.com/nodegit/promisify-node/blob/master/index.js#L156
```

I realize this module is called promisify-node not promisify-js, etc, but just wondering if this dynamic lookup is necessary.

**Comment by maxkorp** [comment]
That's sort of the entiregy of how just doing `promisify('fs')` instead of `promisify(require('fs'))` works. I'd presume it would pack fine if you used the latter, even with how the code already is, or is that incorrect?

**Comment by kmalakoff** [comment]
@maxkorp unfortunately, I do not have control over the use of promisify-node because it is being used by a library that I am using, not directly in my code. More importantly, the problem is that webpack does static analysis at build time, not run time so it actually doesn't depend on what the caller actually uses, but what they may use. 

The section of code starting at line that I referred to above causes the problem since webpack recognizes the unsupported, dynamic pattern and tries to deal with it by pulling in any possible files in the module including README, package.json, etc. 

One could argue it is a webpack problem and on the other hand, it could be argued that dynamic requires are not future proof (I'm sure of the exact details why, but I believe ES6's import may not provide support for dynamic import either so the new import standard is less flexible than Node's require).

If this feature is not actually used in practice (I'm hoping it is just be syntactic sugar that can be easily changed using the solution you suggest), removing the string section lines would solve the problem. If this is a commonly used feature, I'll just continue using my fork where I comment out the lines.

**Comment by tbranyen** [comment]
@kmalakoff I think we can fix this by renaming `require` will you be around anytime soon so we can test this?

**Comment by kmalakoff** [comment]
@tbranyen I'm here now and for the rest of the evening.

**Comment by tbranyen** [comment]
Sure, there is always a way around static analysis.

**Comment by kmalakoff** [comment]
Understood. I'm going to close this since I have stopped using the library that depends on this one...I'll leave you to it to test if / when a need arises.
