### ISSUE TITLE
Leaner version for current-ish node?

### ISSUE THREAD

**Issue by kylecordes** [nodegit/promisify-node#20]
It would be nice to have either a newer version of this library, or a companion library, that leaves the future behind and works specifically with vaguely recent node versions. I believe it could then ditch both dependencies - the "stable" node has had built-in Promise and Object.assign for quite some time as I understand.

**Comment by maxkorp** [comment]
See my comment here. https://github.com/nodegit/promisify-node/issues/23#issuecomment-229818361

promisify node is primarily maintained for nodegit these days, which depends on the custom promise functionality :/

**Comment by tbranyen** [comment]
I would recommend using https://nodejs.org/dist/latest-v10.x/docs/api/util.html#util_util_promisify_original if you're looking for a leaner option.
